name: CI

on: [push]

jobs:
  build:
    runs-on: node:13
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        npm i,
        npm run build,
        cd dist/airtable/
        ls -l.
